package _const

type RequestData struct {
	From       string `json:"from"`
	To         string `json:"to"`
	Resolution string `json:"resolution"`
	Ticker     string `json:"ticker"`
}

var URL = "https://api.tinkoff.ru/trading/symbols/candles"

var QuotesMap = []map[string]string{
	{"FIGI": "BBG000C4LN67", "Tiker": "GRMN", "Name": "Garmin"},
	{"FIGI": "BBG000BKZTP3", "Tiker": "HOG", "Name": "Harley-Davidson"},
	{"FIGI": "BBG000BRXP69", "Tiker": "EW", "Name": "Edwards Lifesciences"},
	{"FIGI": "BBG000BJF1Z8", "Tiker": "FDX", "Name": "FedEx"},
	{"FIGI": "BBG000BCTQ65", "Tiker": "XEL", "Name": "Xcel Energy"},
	{"FIGI": "BBG000BD2NY8", "Tiker": "BF.B", "Name": "Brown-Forman"},
	{"FIGI": "BBG000BSLZY7", "Tiker": "SCHW", "Name": "The Charles Schwab Corporation"},
	{"FIGI": "BBG000M65M61", "Tiker": "UAL", "Name": "United Airlines Holdings"},
	{"FIGI": "BBG000BD8PN9", "Tiker": "BK", "Name": "Bank of New York Mellon"},
	{"FIGI": "BBG000BN84F3", "Tiker": "DGX", "Name": "Quest Diagnostics"},
	{"FIGI": "BBG000BGVW60", "Tiker": "D", "Name": "Dominion Energy Inc"},
	{"FIGI": "BBG000CGJMB9", "Tiker": "ESS", "Name": "Essex Property Trust"},
	{"FIGI": "BBG000BJX8C8", "Tiker": "NOV", "Name": "National Oilwell Varco"},
	{"FIGI": "BBG000BQ5DS5", "Tiker": "NSC", "Name": "Norfolk Southern"},
	{"FIGI": "BBG000BRJ809", "Tiker": "PPG", "Name": "PPG Industries"},
	{"FIGI": "BBG000BRD0D8", "Tiker": "PNC", "Name": "PNC Financial Services"},
	{"FIGI": "BBG000BR14K5", "Tiker": "CB", "Name": "Chubb"},
	{"FIGI": "BBG000BLHRS2", "Tiker": "HSY", "Name": "Hershey"},
	{"FIGI": "BBG000BQ8KV2", "Tiker": "NUE", "Name": "Nucor"},
	{"FIGI": "BBG000BX3BL3", "Tiker": "WY", "Name": "Weyerhaeuser"},
	{"FIGI": "BBG000BH3GZ2", "Tiker": "YUM", "Name": "Yum!"},
	{"FIGI": "BBG000BRNLL2", "Tiker": "ALGN", "Name": "Align Technology"},
	{"FIGI": "BBG005CPNTQ2", "Tiker": "KHC", "Name": "Kraft Heinz"},
	{"FIGI": "BBG000G8N9C6", "Tiker": "JWN", "Name": "Nordstrom"},
	{"FIGI": "BBG000BR37X2", "Tiker": "PGR", "Name": "Progressive"},
	{"FIGI": "BBG000BWQFY7", "Tiker": "WFC", "Name": "Wells Fargo & Company"},
	{"FIGI": "BBG000BK2F42", "Tiker": "FIS", "Name": "Fidelity National Information"},
	{"FIGI": "BBG000C5HS04", "Tiker": "NKE", "Name": "NIKE"},
	{"FIGI": "BBG00BN961G4", "Tiker": "DD", "Name": "DuPont de Nemours Inc"},
	{"FIGI": "BBG000BR2TH3", "Tiker": "PG", "Name": "Procter & Gamble"},
	{"FIGI": "BBG000BQLTW7", "Tiker": "ORCL", "Name": "Oracle"},
	{"FIGI": "BBG000BGRY34", "Tiker": "CVS", "Name": "CVS Health Corporation"},
	{"FIGI": "BBG000KHWT55", "Tiker": "HPQ", "Name": "HP"},
	{"FIGI": "BBG000BNNKG9", "Tiker": "MAS", "Name": "Masco"},
	{"FIGI": "BBG000BS0ZF1", "Tiker": "RL", "Name": "Ralph Lauren"},
	{"FIGI": "BBG000BLXZN1", "Tiker": "TSCO", "Name": "Tractor Supply"},
	{"FIGI": "BBG000BMHYD1", "Tiker": "JNJ", "Name": "Johnson & Johnson"},
	{"FIGI": "BBG000BLPBL5", "Tiker": "AVB", "Name": "AvalonBay Communities"},
	{"FIGI": "BBG000B9ZXB4", "Tiker": "ABT", "Name": "Abbott"},
	{"FIGI": "BBG000BJPDZ1", "Tiker": "ISRG", "Name": "Intuitive Surgical"},
	{"FIGI": "BBG000BWNFZ9", "Tiker": "WDC", "Name": "Western Digital"},
	{"FIGI": "BBG000F1ZSQ2", "Tiker": "MA", "Name": "Mastercard"},
	{"FIGI": "BBG000BPH459", "Tiker": "MSFT", "Name": "Microsoft Corporation"},
	{"FIGI": "BBG000D8RG11", "Tiker": "NRG", "Name": "NRG Energy"},
	{"FIGI": "BBG000B9Z0J8", "Tiker": "PLD", "Name": "Prologis"},
	{"FIGI": "BBG000BNJHS8", "Tiker": "LUV", "Name": "Southwest Airlines"},
	{"FIGI": "BBG000CKGBP2", "Tiker": "GILD", "Name": "GILEAD"},
	{"FIGI": "BBG000RGM5P1", "Tiker": "TEL", "Name": "TE Connectivity"},
	{"FIGI": "BBG000BZX1N5", "Tiker": "AIZ", "Name": "Assurant"},
	{"FIGI": "BBG000C90DH9", "Tiker": "IPG", "Name": "IPG"},
	{"FIGI": "BBG000BBDZG3", "Tiker": "AIG", "Name": "American International Group"},
	{"FIGI": "BBG000B9YJ35", "Tiker": "APH", "Name": "Amphenol"},
	{"FIGI": "BBG000BXMFC3", "Tiker": "URI", "Name": "United Rentals"},
	{"FIGI": "BBG000CB8Q50", "Tiker": "UHS", "Name": "Universal Health Services"},
	{"FIGI": "BBG000C1S2X2", "Tiker": "VRTX", "Name": "Vertex Pharmaceuticals"},
	{"FIGI": "BBG0088CYPX8", "Tiker": "NLSN", "Name": "Nielsen Holdings plc"},
	{"FIGI": "BBG000BCVJ77", "Tiker": "BAX", "Name": "Baxter International"},
	{"FIGI": "BBG000D898T9", "Tiker": "CAH", "Name": "Cardinal Health"},
	{"FIGI": "BBG000BDXCJ5", "Tiker": "CNC", "Name": "Centene Corporation"},
	{"FIGI": "BBG000BS7KS3", "Tiker": "TAP", "Name": "Molson Coors Brewing"},
	{"FIGI": "BBG000C0G1D1", "Tiker": "INTC", "Name": "Intel Corporation"},
	{"FIGI": "BBG003PS7JV1", "Tiker": "ALLE", "Name": "Allegion"},
	{"FIGI": "BBG001D8R5D0", "Tiker": "XYL", "Name": "Xylem"},
	{"FIGI": "BBG000N2HDY5", "Tiker": "ANET", "Name": "Arista Networks Inc"},
	{"FIGI": "BBG000BBDV81", "Tiker": "CTSH", "Name": "Cognizant Technology Solutions"},
	{"FIGI": "BBG000C45984", "Tiker": "L", "Name": "Loews"},
	{"FIGI": "BBG0035M2ZB7", "Tiker": "NWS", "Name": "News Corp"},
	{"FIGI": "BBG000BWGYF8", "Tiker": "VMC", "Name": "Vulcan Materials"},
	{"FIGI": "BBG000BLMZK6", "Tiker": "KMX", "Name": "CarMax"},
	{"FIGI": "BBG00JHNKJY8", "Tiker": "FOX", "Name": "Twenty-First Century Fox"},
	{"FIGI": "BBG000PV27K3", "Tiker": "EXR", "Name": "Extra Space Storage"},
	{"FIGI": "BBG000BMW2Z0", "Tiker": "KMB", "Name": "Kimberly-Clark"},
	{"FIGI": "BBG000L9CV04", "Tiker": "UPS", "Name": "United Parcel Service"},
	{"FIGI": "BBG000BWVSR1", "Tiker": "WM", "Name": "Waste Management"},
	{"FIGI": "BBG000FQRVM3", "Tiker": "WAT", "Name": "Waters"},
	{"FIGI": "BBG000BF0K17", "Tiker": "CAT", "Name": "Caterpillar"},
	{"FIGI": "BBG000D9D830", "Tiker": "ACN", "Name": "Accenture"},
	{"FIGI": "BBG000BM7HL0", "Tiker": "ADSK", "Name": "Autodesk"},
	{"FIGI": "BBG000BG4202", "Tiker": "CPB", "Name": "Campbell Soup"},
	{"FIGI": "BBG000BLW530", "Tiker": "EMN", "Name": "Eastman Chemical Company"},
	{"FIGI": "BBG000DMBXR2", "Tiker": "JPM", "Name": "JPMorgan"},
	{"FIGI": "BBG000BHPL78", "Tiker": "EFX", "Name": "Equifax"},
	{"FIGI": "BBG000BM6788", "Tiker": "IR", "Name": "Ingersoll-Rand"},
	{"FIGI": "BBG000BZCKH3", "Tiker": "MTD", "Name": "Mettler Toledo"},
	{"FIGI": "BBG000BB8SW7", "Tiker": "PKG", "Name": "Packaging Corp of America"},
	{"FIGI": "BBG000BPPN67", "Tiker": "PSA", "Name": "Public Storage"},
	{"FIGI": "BBG000BB5792", "Tiker": "RCL", "Name": "Royal Caribbean Cruises"},
	{"FIGI": "BBG000BQQH30", "Tiker": "COP", "Name": "ConocoPhillips"},
	{"FIGI": "BBG000CHWP52", "Tiker": "DISCA", "Name": "Discovery Communications (A)"},
	{"FIGI": "BBG006Q0HY77", "Tiker": "CFG", "Name": "Citizens Financial Group"},
	{"FIGI": "BBG000BN53G7", "Tiker": "LEG", "Name": "Leggett & Platt"},
	{"FIGI": "BBG00658F3P3", "Tiker": "SYF", "Name": "Synchrony Financial"},
	{"FIGI": "BBG00FWQ4VD6", "Tiker": "ULTA", "Name": "Ulta Beauty"},
	{"FIGI": "BBG000BCZYD3", "Tiker": "BDX", "Name": "Becton, Dickinson and Company"},
	{"FIGI": "BBG000BBD070", "Tiker": "HES", "Name": "Hess"},
	{"FIGI": "BBG000C1FB75", "Tiker": "ICE", "Name": "Intercontinental Exchange"},
	{"FIGI": "BBG000WCFV84", "Tiker": "LYB", "Name": "LyondellBasell"},
	{"FIGI": "BBG000FY4S11", "Tiker": "C", "Name": "Citigroup"},
	{"FIGI": "BBG000BLDV98", "Tiker": "HRB", "Name": "H&R Block"},
	{"FIGI": "BBG000BT9DW0", "Tiker": "SO", "Name": "Southern"},
	{"FIGI": "BBG000BMX289", "Tiker": "KO", "Name": "COCA-COLA"},
	{"FIGI": "BBG000Q3JN03", "Tiker": "RF", "Name": "Regions Financial"},
	{"FIGI": "BBG000BKL348", "Tiker": "GPC", "Name": "Genuine Parts"},
	{"FIGI": "BBG000BR3KL6", "Tiker": "PH", "Name": "Parker-Hannifin"},
	{"FIGI": "BBG000BTVJ25", "Tiker": "SYY", "Name": "Sysco"},
	{"FIGI": "BBG000BVVQQ8", "Tiker": "TXT", "Name": "Textron"},
	{"FIGI": "BBG001QD41M9", "Tiker": "APTV", "Name": "Aptiv"},
	{"FIGI": "BBG000PPFKQ7", "Tiker": "BR", "Name": "Broadridge Financial Solutions"},
	{"FIGI": "BBG000BQVTF5", "Tiker": "PCAR", "Name": "PACCAR"},
	{"FIGI": "BBG000BJL3N0", "Tiker": "FITB", "Name": "Fifth Third Bancorp"},
	{"FIGI": "BBG000BB5373", "Tiker": "WU", "Name": "Western Union"},
	{"FIGI": "BBG000CH5208", "Tiker": "UNH", "Name": "UnitedHealth"},
	{"FIGI": "BBG000BFPK65", "Tiker": "CINF", "Name": "Cincinnati Financial Corporation"},
	{"FIGI": "BBG000BPXVJ6", "Tiker": "RSG", "Name": "Republic Services"},
	{"FIGI": "BBG006G063F9", "Tiker": "INFO", "Name": "IHS Markit"},
	{"FIGI": "BBG000RTDY25", "Tiker": "MSCI", "Name": "MSCI Inc"},
	{"FIGI": "BBG000BKFBD7", "Tiker": "STT", "Name": "State Street"},
	{"FIGI": "BBG000BV8DN6", "Tiker": "TJX", "Name": "TJX"},
	{"FIGI": "BBG000BJ8YN7", "Tiker": "FAST", "Name": "Fastenal Company"},
	{"FIGI": "BBG000C13CD9", "Tiker": "CDNS", "Name": "Cadence Design Systems"},
	{"FIGI": "BBG000BP0KQ8", "Tiker": "EA", "Name": "Electronic Arts"},
	{"FIGI": "BBG000BCMBG4", "Tiker": "FTNT", "Name": "Fortinet Inc"},
	{"FIGI": "BBG000DCGRL8", "Tiker": "IPGP", "Name": "IPG Photonics Corporation"},
	{"FIGI": "BBG000BB6KF5", "Tiker": "MET", "Name": "MetLife"},
	{"FIGI": "BBG000BQC9V2", "Tiker": "NWL", "Name": "Newell Brands"},
	{"FIGI": "BBG000BLBVN4", "Tiker": "BKNG", "Name": "Booking"},
	{"FIGI": "BBG000Q5ZRM7", "Tiker": "DLR", "Name": "Digital Realty"},
	{"FIGI": "BBG000BQ2C28", "Tiker": "NOC", "Name": "Northrop Grumman"},
	{"FIGI": "BBG000MBDGM6", "Tiker": "EQIX", "Name": "Equinix"},
	{"FIGI": "BBG000BJKPG0", "Tiker": "FISV", "Name": "Fiserv"},
	{"FIGI": "BBG000F7RCJ1", "Tiker": "AAP", "Name": "Advance Auto Parts"},
	{"FIGI": "BBG000C0LW92", "Tiker": "BSX", "Name": "Boston Scientific Corporation"},
	{"FIGI": "BBG000BF6LY3", "Tiker": "CCL", "Name": "Carnival"},
	{"FIGI": "BBG000QBR5J5", "Tiker": "DFS", "Name": "Discover Financial Services"},
	{"FIGI": "BBG000BW3299", "Tiker": "UNP", "Name": "Union Pacific Corporation"},
	{"FIGI": "BBG000BKZB36", "Tiker": "HD", "Name": "The Home Depot"},
	{"FIGI": "BBG000HS77T5", "Tiker": "VZ", "Name": "Verizon Communications"},
	{"FIGI": "BBG00FN64XT9", "Tiker": "DXC", "Name": "DXC Technology"},
	{"FIGI": "BBG000BP52R2", "Tiker": "MMM", "Name": "3M Company"},
	{"FIGI": "BBG000C3GN47", "Tiker": "COG", "Name": "Cabot Oil & Gas"},
	{"FIGI": "BBG000BNPSQ9", "Tiker": "INCY", "Name": "Incyte"},
	{"FIGI": "BBG000L4M7F1", "Tiker": "RMD", "Name": "ResMed Inc"},
	{"FIGI": "BBG000BY29C7", "Tiker": "TPR", "Name": "Tapestry"},
	{"FIGI": "BBG000BJQWD2", "Tiker": "AKAM", "Name": "Akamai Technologies"},
	{"FIGI": "BBG000C43RR5", "Tiker": "EBAY", "Name": "eBay"},
	{"FIGI": "BBG000DWG505", "Tiker": "BRK.B", "Name": "Berkshire Hathaway"},
	{"FIGI": "BBG000BFJT36", "Tiker": "CHD", "Name": "Church & Dwight"},
	{"FIGI": "BBG000BHKYH4", "Tiker": "ECL", "Name": "Ecolab"},
	{"FIGI": "BBG000BJ2D31", "Tiker": "SPG", "Name": "Simon Property Group"},
	{"FIGI": "BBG001M8HHB7", "Tiker": "TRIP", "Name": "TripAdvisor"},
	{"FIGI": "BBG000BW8S60", "Tiker": "UTX", "Name": "United Technologies"},
	{"FIGI": "BBG000H3YXF8", "Tiker": "CTAS", "Name": "Cintas"},
	{"FIGI": "BBG000BKTFN2", "Tiker": "HAL", "Name": "Halliburton"},
	{"FIGI": "BBG000BHCP19", "Tiker": "MCHP", "Name": "Microchip Technology"},
	{"FIGI": "BBG000BV59Y6", "Tiker": "TFX", "Name": "Teleflex Inc"},
	{"FIGI": "BBG000BWLMJ4", "Tiker": "WBA", "Name": "Walgreens Boots Alliance"},
	{"FIGI": "BBG000BX57K1", "Tiker": "XRAY", "Name": "Dentsply Sirona"},
	{"FIGI": "BBG000C2ZCH8", "Tiker": "SRE", "Name": "Sempra Energy"},
	{"FIGI": "BBG00DL8NMV2", "Tiker": "FTI", "Name": "TechnipFMC"},
	{"FIGI": "BBG000BV75B7", "Tiker": "TIF", "Name": "Tiffany & Co"},
	{"FIGI": "BBG000BNGTQ7", "Tiker": "LB", "Name": "L Brands"},
	{"FIGI": "BBG000BJBZ23", "Tiker": "MKTX", "Name": "MarketAxess Holdings Inc"},
	{"FIGI": "BBG000BGKTF9", "Tiker": "COF", "Name": "Capital One"},
	{"FIGI": "BBG000BJP882", "Tiker": "FMC", "Name": "FMC"},
	{"FIGI": "BBG000C46HM9", "Tiker": "M", "Name": "Macy's"},
	{"FIGI": "BBG000BR2B91", "Tiker": "PFE", "Name": "Pfizer"},
	{"FIGI": "BBG000BVPV84", "Tiker": "AMZN", "Name": "Amazon.com"},
	{"FIGI": "BBG000BS5CM9", "Tiker": "BXP", "Name": "Boston Properties"},
	{"FIGI": "BBG000FKJRC5", "Tiker": "EL", "Name": "The Estee Lauder Companies"},
	{"FIGI": "BBG000G0Z878", "Tiker": "HIG", "Name": "Hartford Financial Services"},
	{"FIGI": "BBG0059FN811", "Tiker": "KEYS", "Name": "Keysight Technologies Inc"},
	{"FIGI": "BBG000BNFLM9", "Tiker": "LRCX", "Name": "Lam Research"},
	{"FIGI": "BBG008NVB1C0", "Tiker": "MNST", "Name": "Monster Beverage"},
	{"FIGI": "BBG000B9XYV2", "Tiker": "AMT", "Name": "American Tower"},
	{"FIGI": "BBG000C2PW58", "Tiker": "BLK", "Name": "BlackRock"},
	{"FIGI": "BBG000BB6G37", "Tiker": "ADI", "Name": "Analog Devices"},
	{"FIGI": "BBG0035LY913", "Tiker": "NWSA", "Name": "News Corp (A)"},
	{"FIGI": "BBG000C060M4", "Tiker": "AMG", "Name": "Affiliated Managers Group"},
	{"FIGI": "BBG000BVMGF2", "Tiker": "ALL", "Name": "The Allstate Corporation"},
	{"FIGI": "BBG000BP6LJ8", "Tiker": "MO", "Name": "Altria Group"},
	{"FIGI": "BBG000BPQD31", "Tiker": "MYL", "Name": "Mylan NV"},
	{"FIGI": "BBG000BL9JQ1", "Tiker": "HFC", "Name": "HollyFrontier"},
	{"FIGI": "BBG000BPNP00", "Tiker": "MXIM", "Name": "Maxim Integrated Products Inc"},
	{"FIGI": "BBG000BT0CM2", "Tiker": "SIVB", "Name": "SVB Financial Group"},
	{"FIGI": "BBG000PSKYX7", "Tiker": "V", "Name": "Visa"},
	{"FIGI": "BBG000BFVXX0", "Tiker": "CMS", "Name": "CMS Energy Corporation"},
	{"FIGI": "BBG000NV1KK7", "Tiker": "DG", "Name": "Dollar General"},
	{"FIGI": "BBG00BLVZ228", "Tiker": "FTV", "Name": "Fortive"},
	{"FIGI": "BBG000BMY992", "Tiker": "KR", "Name": "Kroger"},
	{"FIGI": "BBG000C3J3C9", "Tiker": "CSCO", "Name": "Cisco"},
	{"FIGI": "BBG000C1XVK6", "Tiker": "RE", "Name": "Everest Re Group"},
	{"FIGI": "BBG00333FYS2", "Tiker": "IQV", "Name": "IQVIA Holdings Inc"},
	{"FIGI": "BBG000BMTFR4", "Tiker": "KLAC", "Name": "KLA-Tencor"},
	{"FIGI": "BBG000C41023", "Tiker": "UDR", "Name": "UDR"},
	{"FIGI": "BBG000R7RDB4", "Tiker": "CXO", "Name": "Concho Resources"},
	{"FIGI": "BBG000DQTXY6", "Tiker": "DHI", "Name": "D.R. Horton"},
	{"FIGI": "BBG000QY3XZ2", "Tiker": "EXPE", "Name": "Expedia"},
	{"FIGI": "BBG000J2XL74", "Tiker": "PM", "Name": "Philip Morris"},
	{"FIGI": "BBG000VPGNR2", "Tiker": "CHTR", "Name": "Charter Communications"},
	{"FIGI": "BBG000D7RKJ5", "Tiker": "EIX", "Name": "Edison International"},
	{"FIGI": "BBG000BXM6V2", "Tiker": "UAA", "Name": "Under Armour"},
	{"FIGI": "BBG000BL8804", "Tiker": "HST", "Name": "Host Hotels & Resorts"},
	{"FIGI": "BBG000BN5HF7", "Tiker": "LEN", "Name": "Lennar"},
	{"FIGI": "BBG00KHY5S69", "Tiker": "AVGO", "Name": "Broadcom"},
	{"FIGI": "BBG000C1BW00", "Tiker": "LMT", "Name": "Lockheed Martin"},
	{"FIGI": "BBG000F0KF42", "Tiker": "STX", "Name": "Seagate"},
	{"FIGI": "BBG000BVP5P2", "Tiker": "SLG", "Name": "SL Green Realty"},
	{"FIGI": "BBG000BBQCY0", "Tiker": "AMD", "Name": "AMD"},
	{"FIGI": "BBG000BMQPL1", "Tiker": "KEY", "Name": "KeyCorp"},
	{"FIGI": "BBG000C8H633", "Tiker": "MRO", "Name": "Marathon Oil"},
	{"FIGI": "BBG000BP1Q11", "Tiker": "SPGI", "Name": "S&P Global"},
	{"FIGI": "BBG000BWBZN1", "Tiker": "VAR", "Name": "Varian Medical Systems"},
	{"FIGI": "BBG000BHLYS1", "Tiker": "ED", "Name": "Consolidated Edison"},
	{"FIGI": "BBG000CXYSZ6", "Tiker": "FFIV", "Name": "F5 Networks"},
	{"FIGI": "BBG000NDYB67", "Tiker": "GM", "Name": "General Motors"},
	{"FIGI": "BBG000BLSL58", "Tiker": "IFF", "Name": "International Flavors & Fragrances"},
	{"FIGI": "BBG000BQZMH4", "Tiker": "PEG", "Name": "Public Service Enterprise Group"},
	{"FIGI": "BBG000C23KJ3", "Tiker": "AES", "Name": "The AES Corporation"},
	{"FIGI": "BBG000BGPTV6", "Tiker": "CMI", "Name": "Cummins"},
	{"FIGI": "BBG000BDDNH5", "Tiker": "BLL", "Name": "Ball Corporation"},
	{"FIGI": "BBG000R7Z112", "Tiker": "DAL", "Name": "Delta Air Lines"},
	{"FIGI": "BBG000BMDBZ1", "Tiker": "JBHT", "Name": "JB Hunt"},
	{"FIGI": "BBG000BT41Q8", "Tiker": "SLB", "Name": "Schlumberger"},
	{"FIGI": "BBG000B9XG87", "Tiker": "AME", "Name": "AMETEK"},
	{"FIGI": "BBG000GXZ4W7", "Tiker": "ANSS", "Name": "ANSYS"},
	{"FIGI": "BBG000BKLH74", "Tiker": "GPS", "Name": "Gap"},
	{"FIGI": "BBG000BC2C10", "Tiker": "APA", "Name": "Apache"},
	{"FIGI": "BBG000BKVJK4", "Tiker": "HAS", "Name": "Hasbro"},
	{"FIGI": "BBG000BY2Y78", "Tiker": "IVZ", "Name": "Invesco"},
	{"FIGI": "BBG00BN969C1", "Tiker": "CTVA", "Name": "Corteva Inc"},
	{"FIGI": "BBG000QW7VC1", "Tiker": "HCA", "Name": "HCA Healthcare"},
	{"FIGI": "BBG000C7LMS8", "Tiker": "AZO", "Name": "AutoZone"},
	{"FIGI": "BBG000BBCDZ2", "Tiker": "ROK", "Name": "Rockwell Automation"},
	{"FIGI": "BBG000C3NTN5", "Tiker": "HOLX", "Name": "Hologic"},
	{"FIGI": "BBG000KLB4Q1", "Tiker": "SWKS", "Name": "Skyworks Solutions"},
	{"FIGI": "BBG000BWCKB6", "Tiker": "VFC", "Name": "VF"},
	{"FIGI": "BBG000DB3KT1", "Tiker": "WLTW", "Name": "Willis Towers Watson"},
	{"FIGI": "BBG000BLNNH6", "Tiker": "IBM", "Name": "IBM"},
	{"FIGI": "BBG000BC1L02", "Tiker": "AOS", "Name": "A. O. Smith Corporation"},
	{"FIGI": "BBG000BGYWY6", "Tiker": "ORLY", "Name": "O'Reilly Automotive"},
	{"FIGI": "BBG000BN2DC2", "Tiker": "CRM", "Name": "Salesforce"},
	{"FIGI": "BBG000BLZRJ2", "Tiker": "MS", "Name": "Morgan Stanley"},
	{"FIGI": "BBG000BC15S7", "Tiker": "AON", "Name": "Aon PLC"},
	{"FIGI": "BBG000GPXKX9", "Tiker": "FLT", "Name": "FleetCor Technologies Inc"},
	{"FIGI": "BBG000CN3S73", "Tiker": "KIM", "Name": "Kimco Realty"},
	{"FIGI": "BBG000BSXQV7", "Tiker": "SHW", "Name": "Sherwin-Williams"},
	{"FIGI": "BBG000BWP7D9", "Tiker": "WEC", "Name": "WEC Energy Group"},
	{"FIGI": "BBG000BH4R78", "Tiker": "DIS", "Name": "Walt Disney"},
	{"FIGI": "BBG000BLCPY4", "Tiker": "HP", "Name": "Helmerich & Payne"},
	{"FIGI": "BBG0058KMH30", "Tiker": "HLT", "Name": "Hilton"},
	{"FIGI": "BBG00GVR8YQ9", "Tiker": "LIN", "Name": "Linde"},
	{"FIGI": "BBG000BVDLH9", "Tiker": "TMO", "Name": "Thermo Fisher Scientific"},
	{"FIGI": "BBG000DKCC19", "Tiker": "TSN", "Name": "Tyson Foods"},
	{"FIGI": "BBG000BWVCP8", "Tiker": "WMB", "Name": "The Williams Companies"},
	{"FIGI": "BBG009S39JX6", "Tiker": "GOOGL", "Name": "Alphabet Class A"},
	{"FIGI": "BBG009S3NB30", "Tiker": "GOOG", "Name": "Google"},
	{"FIGI": "BBG000D6L294", "Tiker": "XEC", "Name": "Cimarex Energy"},
	{"FIGI": "BBG009DTD8H2", "Tiker": "UA", "Name": "Under Armour (C)"},
	{"FIGI": "BBG000DD3510", "Tiker": "AIV", "Name": "Apartment Investment & Management"},
	{"FIGI": "BBG000BJ49H3", "Tiker": "BWA", "Name": "BorgWarner"},
	{"FIGI": "BBG000BFNR17", "Tiker": "ADS", "Name": "Alliance Data Systems"},
	{"FIGI": "BBG000BRJL00", "Tiker": "PPL", "Name": "PPL"},
	{"FIGI": "BBG000H556T9", "Tiker": "HON", "Name": "Honeywell"},
	{"FIGI": "BBG000PXDL44", "Tiker": "LKQ", "Name": "LKQ Corporation"},
	{"FIGI": "BBG00JHNJW99", "Tiker": "FOXA", "Name": "Twenty-First Century Fox (A)"},
	{"FIGI": "BBG000CX0P89", "Tiker": "GPN", "Name": "Global Payments"},
	{"FIGI": "BBG000BSC0K9", "Tiker": "DLTR", "Name": "Dollar Tree"},
	{"FIGI": "BBG000BHLYP4", "Tiker": "CME", "Name": "CME GROUP"},
	{"FIGI": "BBG000BG3445", "Tiker": "COO", "Name": "The Cooper Companies"},
	{"FIGI": "BBG000BCQZS4", "Tiker": "AXP", "Name": "American Express"},
	{"FIGI": "BBG000F86GP6", "Tiker": "MCO", "Name": "Moody's"},
	{"FIGI": "BBG000BCQ4P6", "Tiker": "AVY", "Name": "Avery Dennison"},
	{"FIGI": "BBG000F5VVB6", "Tiker": "NDAQ", "Name": "Nasdaq"},
	{"FIGI": "BBG000BL9C59", "Tiker": "MAC", "Name": "Macerich"},
	{"FIGI": "BBG000BFXHL6", "Tiker": "MOS", "Name": "Mosaic"},
	{"FIGI": "BBG000BNSZP1", "Tiker": "MCD", "Name": "Mc'DONALDS"},
	{"FIGI": "BBG000D9KWL9", "Tiker": "MTB", "Name": "M&T Bank"},
	{"FIGI": "BBG000G6Y5W4", "Tiker": "MKC", "Name": "McCormick & Co"},
	{"FIGI": "BBG000BCZL41", "Tiker": "VRSK", "Name": "Verisk Analytics"},
	{"FIGI": "BBG000BVV7G1", "Tiker": "TXN", "Name": "Texas Instruments"},
}

func GetQuotes() []string {
	var quotes = make([]string, 0, len(QuotesMap))
	for k := range QuotesMap {
		quotes = append(quotes, k)
	}
	return quotes
}
